title: "Clément LAVAUD"
description: "PhD Student in Applied Mathematics"
#theme: minima
plugins: []
markdown: kramdown
show_excerpts: true
defaults:
  - scope:
      path: ""
    values:
      css: "/assets/css/style.css"


# Links for header navigation
nav:
  - title: "Home"
    url: /
  - title: "Research"
    url: /research
  - title: "Publications"
    url: /publications
  - title: "CV"
    url: /cv
  - title: "Contact"
    url: /contact

# Optional social icons
github_username: clementlavaud
google_scholar: "https://scholar.google.com/"

minima:
  skin: classic
sass:
  style: compressed

